[package]
name = "shadow-swap"
version = "0.1.0"
edition = "2024"


[dependencies]
actix-web = "4.9"
actix-cors = "0.7"
tokio = { version = "1.44", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.2.0", features = ["postgres", "r2d2", "chrono", "uuid", "numeric", "serde_json"] }
diesel_migrations = { version = "2.2.0", features = ["postgres"] }
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.0", features = ["v4"] }
reqwest = { version = "0.12", features = ["json"] }
ecies = { version = "0.2", default-features = false, features = ["pure"] }
secp256k1 = { version = "0.28", features = ["rand", "recovery"] }
hex = "0.4"
r2d2 = "0.8"
log = "0.4"
dotenv = "0.15"
anyhow = "1.0"
hmac = "0.12.1"
ethers = "2.0"
toml = "0.8"
sha2 = "0.10"
serial_test = "3.0"
lazy_static = "1.5.0"
clap = "4.5.54"
