[package]
name = "solver"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
ethers = { version = "2.0", features = ["ws", "rustls"] }
dotenv = "0.15"
anyhow = "1.0"
tracing = "0.1"
actix-web = "4.9"
actix-cors = "0.7"